
server:
  port: 8083
  servlet:
    context-path: /portfolio
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect